hashirim_shelanu/urls.py
from django.urls import path

from . import views

app_name = "hashirim_shelanu"
urlpatterns = [
    path("", views.search, name="search"),
    path("filter/", views.search_filter, name="filter"),
    path("viewsong/<int:song_id>/", views.viewsong, name="viewsong"),
    path("viewsong/<int:song_id>/download_chordpro/", views.download_chordpro, name="download_chordpro"),
    path("viewsong/<int:song_id>/download_pdf/", views.download_pdf, name="download_pdf"),
    path("viewartist/<int:artist_id>/", views.viewartist, name="viewartist"),
    path("viewprayer/<int:prayer_id>/", views.viewprayer, name="viewprayer"),
]

service_generator/urls.py
from django.urls import path

from . import views

app_name = "service_generator"
urlpatterns = [
    path("", views.landing, name="landing"),
    path("beginservice/<int:service_id>", views.begin_service, name="begin_service"),
    path("viewservicetype/<int:service_id>", views.view_service_type, name="view_service_type"),
    path("generatetemplate", views.generate_template, name="generate_template"),
    path("startnextsection", views.start_next_section, name="start_next_section")
]

tfilah_toolbox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from . import views

urlpatterns = [
    path("hashirim_shelanu/", include("hashirim_shelanu.urls")),
    path("service_generator/", include("service_generator.urls")),
    path("admin/", admin.site.urls),
    path("", views.index),
    path("login", LoginView.as_view(template_name="tfilah_toolbox/login.html"), name="login"),
    path("logout", LogoutView.as_view(), name="logout")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_generator/models.py
# from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
# from django.contrib.postgres.fields import ArrayField
from django.db import models
# from django.db.models.constraints import Deferrable, UniqueConstraint

from hashirim_shelanu.models import Prayer, Song


# Create your models here.
class Section(models.Model):
    name = models.CharField(max_length=200)
    display_name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    prayers = models.ManyToManyField(Prayer, through="SectionPrayer")


class SectionPrayer(models.Model):
    prayer = models.ForeignKey(Prayer, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    index = models.PositiveSmallIntegerField(unique=True)

    class Meta:
        ordering = ["index"]


class ServiceType(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    # prayers = models.ManyToManyField(Prayer, through="PrayerPosition")
    sections = models.ManyToManyField(Section, through="ServiceTypeSection")

    def __str__(self):
        return self.name


class ServiceTypeSection(models.Model):
    service_type = models.ForeignKey(ServiceType, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    index = models.PositiveSmallIntegerField(unique=True)

    class Meta:
        ordering = ["index"]
        # TODO: Switch to PostgreSQL, which supports this
        # constraints = [UniqueConstraint(
        #     name="prayer_unique_index",
        #     fields=["index"],
        #     deferrable=Deferrable.DEFERRED
        # )]

# ********************************
# ****** REMOVED FROM SPEC *******
# ********************************
#
# class ServiceElement(models.Model):
#     class ElementTypes(models.IntegerChoices):
#         SONG = 1, "Song"
#         PRAYER = 2, "Prayer"
#         READING = 3, "Reading"
#         IYUN = 4, "Iyun"
#         OTHER = 5, "Other"
#
#         @classmethod
#         def get_limit_query(cls) -> models.Q:
#             limit = models.Q()
#             for _, name in cls.choices:
#                 limit |= models.Q(app_label="service_generator", model=name + "_Element")
#             return limit
#
#     element_type = models.ForeignKey(
#         ContentType,
#         on_delete=models.CASCADE,
#         limit_choices_to=ElementTypes.get_limit_query()
#     )
#     object_id = models.PositiveIntegerField()
#     object = GenericForeignKey("element_type", "object_id")
#     point = models.CharField(max_length=200)
#
#     # supporting = ArrayField(models.CharField(max_length=200))
#     # TEMPORARY SOLUTION WITHOUT POSTGRES
#     _supporting = models.CharField(max_length=2000, blank=True)
#
#     @property
#     def supporting(self) -> list[str]:
#         return self._supporting.split(", ")
#
#     @supporting.setter
#     def supporting(self, value: list[str]):
#         self._supporting = ", ".join(value)
#         self.save()
#
#     def get_supporters_str(self) -> str:
#         return self._supporting
#
# class Service(models.Model):
#     title = models.CharField(max_length=200)
#     description = models.TextField(blank=True)
#     service_type = models.ForeignKey(Service_Type, on_delete=models.CASCADE)
#     element_list = models.ManyToManyField(Service_Element, through="Element_Position")
#
# class ElementPosition(models.Model):
#     element = models.ForeignKey(Service_Element, on_delete=models.CASCADE)
#     service = models.ForeignKey(Service, on_delete=models.CASCADE)
#     index = models.PositiveSmallIntegerField(unique=True)
#
#     class Meta:
#         ordering = ["index"]
#         # constraints = [UniqueConstraint(
#         #     name="element_unique_index",
#         #     fields=["index"],
#         #     deferrable=Deferrable.DEFERRED
#         # )]
#
#
# class GenericElement(models.Model):
#     def get_short_name(self) -> str:
#         raise NotImplementedError("Cannot run abstract method")
#
#     def __str__(self):
#         return self.get_short_name()
#
#     class Meta:
#         abstract = True
#
#
# class SongElement(GenericElement, Song):
#     def get_short_name(self) -> str:
#         return self.title
#
#     class Meta(GenericElement.Meta):
#         proxy = True
#
#
# class PrayerElement(GenericElement, Prayer):
#     def get_short_name(self) -> str:
#         return self.name
#
#     class Meta(GenericElement.Meta):
#         proxy = True
#
#
# class ReadingElement(GenericElement):
#     title = models.CharField(max_length=200)
#     author = models.CharField(max_length=200, blank=True)
#     text = models.TextField(blank=True)
#
#     def get_short_name(self) -> str:
#         return self.title
#
#
# class IyunElement(GenericElement):
#     title = models.CharField(max_length=200)
#     description = models.TextField(blank=True)
#
#     def get_short_name(self) -> str:
#         return self.title
#
#
# class OtherElement(GenericElement):
#     title = models.CharField(max_length=200)
#     description = models.TextField(blank=True)
#
#     def get_short_name(self) -> str:
#         return self.title

service_generator/views.py
import io
from typing import Optional
from xml.etree import ElementTree

from django.http import HttpRequest, HttpResponse, FileResponse
from django.shortcuts import get_object_or_404, render

from .models import ServiceType, ServiceTypeSection


# Create your views here.


def landing(request: HttpRequest) -> HttpResponse:
    return render(request, "service_generator/landing.html", {"service_types": ServiceType.objects.all})


def begin_service(request: HttpRequest, service_id: int) -> HttpResponse:
    return render(request, "service_generator/beginservice.html", {
        "service_type": get_object_or_404(ServiceType, pk=service_id)
    })


def generate_template(request: HttpRequest, service_id: int) -> HttpResponse:
    title = request.POST["title"]
    service = ElementTree.Element("service")
    metadata = ElementTree.SubElement(service, "metadata")
    # noinspection PyTypeChecker
    metadata.extend([
        ElementTree.Element("servicetype", text=ServiceType.objects.get(id=service_id)),
        ElementTree.Element("occasion", text=request.POST.get("occasion", "")),
        ElementTree.Element("community", text=request.POST.get("community", "")),
        ElementTree.Element("theme", text=request.POST.get("theme", "")),
        ElementTree.Element("mood", text=request.POST.get("mood", "")),
        ElementTree.Element("time", text=request.POST.get("time", "")),
        ElementTree.Element("parashah", text=request.POST.get("parashah", "")),
        ElementTree.Element("space", text=request.POST.get("space", ""))
    ])
    style = ElementTree.SubElement(metadata, "style")
    # TODO add style
    request.session["service"] = service
    request.session["service_title"] = title
    return start_next_section(request, service_id, 1)


def start_next_section(request: HttpRequest, service_id: int, next_section: int) -> HttpResponse:
    if len((service_type := ServiceType.objects.get(id=service_id)).sections) < next_section:
        return finalize_service(request)
    service = request.session["service"]
    section = service_type.sections[next_section]
    service.append(ElementTree.Element("section", {"name": section.display_name}))
    return next_element(request, service_id, next_section, 1)


def _next_prayer(service_type: ServiceType, section_index: int, prayer_index: int) -> tuple[Optional[str], Optional[str]]:
    """Return the name of the next prayer. If that prayer is in a new section, return the name of that section too."""
    if len(service_type.sections[section_index].prayers) > prayer_index:
        # Next prayer is in this section
        return None, service_type.sections[section_index].prayers[prayer_index + 1].name
    if len(service_type.sections) > section_index:
        # Go to next section
        return service_type.sections[section_index + 1].name, service_type.sections[section_index + 1].prayers[1].name
    # Finalize
    return None, None


def next_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    if len((service_type := ServiceType.objects.get(id=service_id)).sections[section_index].prayers) < prayer_index:
        return start_next_section(request, service_id, section_index + 1)
    return render(request, "service_generator/nextelement.html", {
        "service_type": service_type,
        "section": (section_ := service_type[section_index]),
        "prayer": section_[prayer_index],
        "next_prayer_name": _next_prayer(service_type, section_index, prayer_index)
    })


def add_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    if not request.POST["element_type"]:
        return next_element(request, service_id, section_index, prayer_index + 1)
    return render(request, f"service_generator/add{request.POST['element_type']}element", {
        "service_type": (service_type := ServiceType.objects.get(id=service_id)),
        "section": (section_ := service_type[section_index]),
        "prayer": section_[prayer_index]
    })


def add_song_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    service = request.session["service"]
    curr_section = service[-1]
    new_element = ElementTree.SubElement(curr_section, "element", {"type": "song", "id": request.POST["song_id"]})
    new_element.extend([

    ])
    return next_element(request, service_id, section_index, prayer_index)


def add_prayer_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    # TODO
    return next_element(request, service_id, section_index, prayer_index)


def add_reading_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    # TODO
    return next_element(request, service_id, section_index, prayer_index)


def add_iyun_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    # TODO
    return next_element(request, service_id, section_index, prayer_index)


def add_other_element(request: HttpRequest, service_id: int, section_index: int, prayer_index: int) -> HttpResponse:
    # TODO
    return next_element(request, service_id, section_index, prayer_index)


def finalize_service(request: HttpRequest) -> HttpResponse:
    service = request.session["service"]
    title = request.session["service_title"]
    del request.session["service"]
    del request.session["service_title"]
    return render(request, "service_generator/viewservice.html", {"service": service, "service_title": title})


def download_xml(request: HttpRequest, service: str, title: str) -> FileResponse:
    xml = ElementTree.fromstring(service)
    tree = ElementTree.ElementTree(xml)
    buffer = io.BytesIO()
    tree.write(buffer, "utf-8", True)
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename=f"{title}.xml")


def download_pdf(request: HttpRequest, service: str, title: str) -> FileResponse: pass


def upload_xml(request: HttpRequest) -> HttpResponse:
    # TODO work file magic
    service, title = None
    return render(request, "service_generator/viewservice.html", {"service": service, "service_title": title})


def view_service_type(request: HttpRequest, service_id: int) -> HttpResponse:
    service = get_object_or_404(ServiceType, pk=service_id)
    return render(request, "service_generator/viewservicetype.html", {"service_type": service})


def view_section(request: HttpRequest, service_type_section_id: int) -> HttpResponse:
    service_type_section = get_object_or_404(ServiceTypeSection, pk=service_type_section_id)
    return render(request, "service_generator/viewsection.html", {"service_type_section": service_type_section})

service_generator/templates/service_generator/beginservice.html
{% extends "tfilah_toolbox/base.html" %}

{% block title %}Service Generator | {{ service_type.name }}{% endblock %}

{% block content %}
    <form action="{% url 'service_generator:generate_template' %}" method="POST">
        <div>
            <h2>Basic Info</h2>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" placeholder="Title">
            <!-- TODO -->
        </div>
    </form>
{% endblock %}

service_generator/templates/service_generator/landing.html
{% extends "tfilah_toolbox/base.html" %}

{% block title %}T'filah Toolbox | Service Generator{% endblock %}

{% block content %}
    <ul>
        {% for service in service_types %}
            <li>
                <h4>{{ service }}</h4>
                <a href="{% url 'service_generator:view_service_type' service.id %}">More Info</a>
                <a href="{% url 'service_generator:begin_service' service.id %}">Begin Service</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

service_generator/templates/service_generator/nextelement.html
<!DOCTYPE html>
{% load static %}
<html lang="en-us">
    <head>
        <meta charset="utf-8">
        <title>T'filah Toolbox | Service Generator</title>
        <link rel="stylesheet" type="text/css" href="{% static 'tfilah_toolbox/style.css' %}">
    </head>
    <body>
        {% include "tfilah_toolbox/header.html" %}
        <main>
            <p>Current section: <a href="{% url 'service_generator:view_section' section.id %}">{{ section }}</a></p>
            <p>Current prayer: <a href="{% url 'hashirim_shelanu:viewprayer' prayer.id %}">{{ prayer }}</a></p>
            <form action="{% url 'service_generator:add_element' %}" method="POST">
                <fieldset>
                    <legend>Choose element type to add:</legend>

                    <input type="radio" name="element_type" id="element-type-song" value="song">
                    <label for="element-type-song">Song (from the Hashirim Shelanu database)</label>

                    <input type="radio" name="element_type" id="element-type-prayer" value="prayer">
                    <label for="element-type-prayer">Prayer (e.g. read with no melody or standard nusach)</label>

                    <input type="radio" name="element_type" id="element-type-reading" value="reading">
                    <label for="element-type-reading">Reading</label>

                    <input type="radio" name="element_type" id="element-type-iyun" value="iyun">
                    <label for="element-type-iyun">Iyun (intentional moment)</label>

                    <input type="radio" name="element_type" id="element-type-other" value="other">
                    <label for="element-type-other">Other</label>

                    <input type="radio" name="element_type" id="element-type-continue" value="">
                    <label for="element-type-continue">
                        {% if next_prayer_name.1 == None %}
                            <strong>Finalize service</strong>
                        {% else %}
                            Continue to next
                            {% if next_prayer_name.0 == None %}
                                prayer ({{ next_prayer_name.1 }})
                            {% else %}
                                section ({{ next_prayer_name.0 }}&mdash;{{ next_prayer_name.1 }})
                            {% endif %}
                        {% endif %}
                    </label>
                </fieldset>
                <button type="submit">Add</button>
            </form>
        </main>
        {% include "tfilah_toolbox/footer.html" %}
    </body>
</html>

service_generator/templates/service_generator/search.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'service_generator/search.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'service_generator/style.css' %}">
        <title>Service Generator | Search</title>
    </head>
    <body>
        {% include "service_generator/header.html" %}
        <main>
            <form action="{% url 'service_generator:filter' %}" method="GET">
                <input type="text" name="filter_text" value="{{ filter_text }}">
                <fieldset>
                    <legend>Search by:</legend>

                    <input type="checkbox" name="filter_by_title" id="filter-by-title">
                    <label for="filter-by-title">Title</label>

                    <input type="checkbox" name="filter_by_artist" id="filter-by-artist">
                    <label for="filter-by-artist">Artist</label>

                    <input type="checkbox" name="filter_by_prayer" id="filter-by-prayer">
                    <label for="filter-by-prayer">Prayer</label>
                </fieldset>
                <fieldset>
                    <legend>Order by:</legend>

                    <input type="radio" name="order_by" id="order-by-title" value="title" {% if order_by == "title" %}checked{% endif %}>
                    <label for="order-by-title">Title</label>

                    <input type="radio" name="order_by" id="order-by-artist" value="artist" {% if order_by == "artist" %}checked{% endif %}>
                    <label for="order-by-artist">Artist</label>

                    <input type="radio" name="order_by" id="order-by-prayer" value="prayer" {% if order_by == "prayer" %}checked{% endif %}>
                    <label for="forder-by-prayer">Prayer</label>
                </fieldset>
                <button type="submit">Search</button>
            </form>
            <table>
                <tr>
                    <th>Song Title</th>
                    <th>Artist</th>
                    <th>Prayer</th>
                </tr>
                {% for song in song_list %}
                    <tr>
                        <td><a href="{% url 'service_generator:viewsong' song.id %}">{{ song.title }}</a></td>
                        <td><a href="{% url 'service_generator:viewartist' song.artist.id %}">{{ song.artist.name }}</a></td>
                        <td><a href="{% url 'service_generator:viewprayer' song.prayer.id %}">{{ song.prayer.name }}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </main>
        {% include "service_generator/footer.html" %}
    </body>
</html>

service_generator/templates/service_generator/viewartist.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Service Generator | {{ artist.name }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'service_generator/style.css' %}">
    </head>
    <body>
        {% include "service_generator/header.html" %}
        <main>
            <h1>{{ artist.name }}</h1>
        </main>
        {% include "service_generator/footer.html" %}
    </body>
</html>

service_generator/templates/service_generator/viewprayer.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Service Generator | {{ prayer.name }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'service_generator/style.css' %}">
    </head>
    <body>
        {% include "service_generator/header.html" %}
        <main>
            <h1>{{ prayer.name }}</h1>
            <p>{{ prayer.description }}</p>
        </main>
        {% include "service_generator/footer.html" %}
    </body>
</html>

service_generator/templates/service_generator/viewsection.html
<!--TODO-->

service_generator/templates/service_generator/viewservicetype.html
{% extends "tfilah_toolbox/base.html" %}

{% block title %}Service Generator | {{ service_type }}{% endblock %}

{% block content %}
    <p><a href="#" onclick="history.back(); return false;">&lt; Go back</a></p>
    <h1>{{ service_type }}</h1>
    <p>{{ service_type.description }}</p>
    <p>Prayers:</p>
    <ol>
        {% for prayer in service_type.prayers.all %}
            <li><a href="{% url 'hashirim_shelanu:viewprayer' prayer.id %}">{{ prayer }}</a></li>
        {% endfor %}
    </ol>
{% endblock %}

service_generator/templates/service_generator/viewsong.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Service Generator | "{{ song.title }}" &mdash; {{ song.artist.name }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'service_generator/viewsong.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'service_generator/style.css' %}">
    </head>
    <body>
        {% include "service_generator/header.html" %}
        <main>
            <div id="main-head">
                <p><a href="{% url 'service_generator:search' %}">&lt; Go back</a></p>
                <h2>{{ song.title }}</h2>
                <h3>{{ song.artist }}</h3>
                <p>Prayer: <b>{{ song.prayer.name }}</b></p>
                <form action="{% url 'service_generator:download_chordpro' song.id %}" method="GET">
                    <button type="submit">Download ChordPro</button>
                </form>
                <form action="{% url 'service_generator:download_pdf' song.id %}" method="GET">
                    <button type="submit">Download PDF</button>
                </form>
            </div>
            <div id="chordsheet-display">
                {{ chordsheet_html|safe }}
            </div>
            <div id="chordsheet-contributor">
                <i>Contributed by {{ song.chordsheet.list_contributors }}</i>
            </div>
        </main>
        {% include "service_generator/footer.html" %}
    </body>
</html>