hashirim_shelanu/urls.py
from django.urls import path

from . import views

app_name = "hashirim_shelanu"
urlpatterns = [
    path("", views.search, name="search"),
    path("filter/", views.search_filter, name="filter"),
    path("viewsong/<int:song_id>/", views.viewsong, name="viewsong"),
    path("viewsong/<int:song_id>/download_chordpro/", views.download_chordpro, name="download_chordpro"),
    path("viewsong/<int:song_id>/download_pdf/", views.download_pdf, name="download_pdf"),
    path("viewartist/<int:artist_id>/", views.viewartist, name="viewartist"),
    path("viewprayer/<int:prayer_id>/", views.viewprayer, name="viewprayer"),
]

tfilah_toolbox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from . import views

urlpatterns = [
    path("hashirim_shelanu/", include("hashirim_shelanu.urls")),
    path("service_generator/", include("service_generator.urls")),
    path("admin/", admin.site.urls),
    path("", views.index),
    path("login", LoginView.as_view(template_name="tfilah_toolbox/login.html"), name="login"),
    path("logout", LogoutView.as_view(), name="logout")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hashirim_shelanu/models.py
import io

from chopro import chopro2html
from django.core.validators import FileExtensionValidator
from django.db import models
from weasyprint import HTML, CSS


class PrayerTag(models.Model):
    name = models.SlugField(max_length=100)

    def __str__(self):
        return "#" + self.name


class Prayer(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    tags = models.ManyToManyField(PrayerTag, related_name="prayers", blank=True)

    def __str__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to="artists/", blank=True, null=True)

    def __str__(self):
        return self.name if self.name != "Unknown" else f"Unknown (ID {self.id})"


class SongTag(models.Model):
    name = models.SlugField(max_length=100)

    def __str__(self):
        return "#" + self.name


class Song(models.Model):
    prayer = models.ForeignKey(Prayer, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    release_year = models.PositiveSmallIntegerField(blank=True, null=True)
    tags = models.ManyToManyField(SongTag, related_name="songs", blank=True)

    spotify = models.CharField(max_length=50, blank=True, help_text="Just the ID, for example: 2aSi2nkU99ZaaOg2gB2hd5")
    apple_music = models.CharField(max_length=30, blank=True,
                                   help_text="Just the album and song IDs. for example: 1451484697?i=1451484701")
    youtube = models.CharField(max_length=20, blank=True, help_text="Just the ID, for example: VEJHr0BRh2c")



    def __str__(self):
        return f"{self.title} ({self.artist})"


class ChordsheetContributor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Chordsheet(models.Model):
    file = models.FileField(upload_to="chordsheets/", validators=[FileExtensionValidator(["pro"])])
    contributors = models.ManyToManyField(ChordsheetContributor)
    song = models.OneToOneField(Song, on_delete=models.CASCADE, primary_key=True)

    def get_pdf(self) -> io.BytesIO:
        buffer = io.BytesIO()

        self.file.open("r")
        chordsheet_html = HTML(string=chopro2html(self.file.read()) +
                               f"<div id=chordsheet-contributor>"
                               f"    <i>Contributed by {str(self.list_contributors)}</i>"
                               f"</div>")
        chordsheet_css = CSS(string="div.chords-lyrics-line {"
                             "   display: flex;"
                             "   font-family: Roboto Mono, monospace;"
                             "}"
                             "#chordsheet-contributor {"
                             "   padding-top: 10px;"
                             "}"
                             "div.chords:empty::before {"
                             "   content: ' ';"
                             "   white-space: pre;"
                             "}")
        self.file.close()

        chordsheet_html.write_pdf(buffer, stylesheets=[chordsheet_css])
        buffer.seek(0)
        return buffer

    @property
    def list_contributors(self) -> str:
        contributors: models.QuerySet[ChordsheetContributor] = self.contributors.all()
        if len(contributors) == 1:
            return str(contributors[0])
        if len(contributors) == 2:
            return str(contributors[0]) + " and " + str(contributors[1])
        contributor_strings: list[str] = [str(contributor) for contributor in contributors]
        contributor_strings[-1] = "and " + str(contributors[-1])
        return ", ".join(contributor_strings)

hashirim_shelanu/views.py
from chopro import chopro2html

from django.db.models import Q, QuerySet
from django.http import FileResponse, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Artist, Prayer, Song


def search(request: HttpRequest) -> HttpResponse:
    return render(request, "hashirim_shelanu/search.html",
                  {"song_list": Song.objects.all, "filter_text": "", "order_by": "title", "select": {
                      "title": True,
                      "artist": False,
                      "prayer": False
                  }, "include_tags": False})


def search_filter(request: HttpRequest) -> HttpResponse:
    filter_by = {
        "title": "filter_by_title" in request.GET,
        "artist": "filter_by_artist" in request.GET,
        "prayer": "filter_by_prayer" in request.GET
    }
    if not filter_by["title"] and not filter_by["artist"] and not filter_by["prayer"]:
        filter_by["title"] = filter_by["artist"] = filter_by["prayer"] = True

    filter_text = request.GET["filter_text"]
    query: Q = (
            (Q(title__icontains=filter_text)
             | (Q(tags__name__icontains=filter_text) if "include_tags" in request.GET else Q())
             if filter_by["title"] else Q())
            | (Q(artist__name__icontains=filter_text) if filter_by["artist"] else Q())
            | (Q(prayer__name__icontains=filter_text)
               | (Q(prayer__tags__name__icontains=filter_text) if "include_tags" in request.GET else Q())
               if filter_by["prayer"] else Q())
    )
    song_list: QuerySet[Song] = Song.objects.filter(query).distinct().order_by(request.GET["order_by"])

    return render(request, "hashirim_shelanu/search.html", {
        "song_list": song_list,
        "filter_text": filter_text,
        "order_by": request.GET["order_by"],
        "select": filter_by,
        "include_tags": "include_tags" in request.GET
    })


def viewsong(request: HttpRequest, song_id: int) -> HttpResponse:
    song = get_object_or_404(Song, pk=song_id)
    if hasattr(song, "chordsheet"):
        song.chordsheet.file.open("r")
        chordsheet_html: str = chopro2html(song.chordsheet.file.read())
        song.chordsheet.file.close()
    else:
        chordsheet_html = ""
    return render(request, "hashirim_shelanu/viewsong.html", {"song": song, "chordsheet_html": chordsheet_html})


def download_chordpro(request: HttpRequest, song_id: int) -> FileResponse:
    return FileResponse(get_object_or_404(Song, pk=song_id).chordsheet.file, as_attachment=True)


def download_pdf(request: HttpRequest, song_id: int) -> FileResponse:
    song = get_object_or_404(Song, pk=song_id)
    return FileResponse(
        song.chordsheet.get_pdf(),
        as_attachment=True,
        filename=song.title + "_" + song.artist.name + ".pdf"
    )


def viewartist(request: HttpRequest, artist_id: int) -> HttpResponse:
    artist = get_object_or_404(Artist, pk=artist_id)
    return render(request, "hashirim_shelanu/viewartist.html", {"artist": artist})


def viewprayer(request: HttpRequest, prayer_id: int) -> HttpResponse:
    prayer = get_object_or_404(Prayer, pk=prayer_id)
    return render(request, "hashirim_shelanu/viewprayer.html", {"prayer": prayer})

hashirim_shelanu/templates/hashirim_shelanu/search.html
{% extends "tfilah_toolbox/base.html" %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" type="text/css" href="{% static 'hashirim_shelanu/search.css' %}">
{% endblock %}

{% block title %}T'filah Toolbox | Hashirim Shelanu{% endblock %}

{% block content %}
    <form action="{% url 'hashirim_shelanu:filter' %}" method="GET">
        <label for="filter-text">Search: </label>
        <input type="text" name="filter_text" id="filter-text" placeholder="Search text" value="{{ filter_text }}">
        <fieldset>
            <legend>Search by:</legend>

            <input type="checkbox" name="filter_by_title" id="filter-by-title" {% if select.title %}checked{% endif %}>
            <label for="filter-by-title">Title</label>

            <input type="checkbox" name="filter_by_artist" id="filter-by-artist" {% if select.artist %}checked{% endif %}>
            <label for="filter-by-artist">Artist</label>

            <input type="checkbox" name="filter_by_prayer" id="filter-by-prayer" {% if select.prayer %}checked{% endif %}>
            <label for="filter-by-prayer">Prayer</label>
        </fieldset>
        <fieldset>
            <legend>Order by:</legend>

            <input type="radio" name="order_by" id="order-by-title" value="title" {% if order_by == "title" %}checked{% endif %}>
            <label for="order-by-title">Title</label>

            <input type="radio" name="order_by" id="order-by-artist" value="artist" {% if order_by == "artist" %}checked{% endif %}>
            <label for="order-by-artist">Artist</label>

            <input type="radio" name="order_by" id="order-by-prayer" value="prayer" {% if order_by == "prayer" %}checked{% endif %}>
            <label for="order-by-prayer">Prayer</label>
        </fieldset>
        <input type="checkbox" name="include_tags" id="include-tags" {% if include_tags %}checked{% endif %}>
        <label for="include-tags">Include tags in search</label>
        <button type="submit">Search</button>
    </form>
    <table>
        <tr>
            <th>Song Title</th>
            <th>Artist</th>
            <th>Prayer</th>
        </tr>
        {% for song in song_list %}
            <tr>
                <td><a href="{% url 'hashirim_shelanu:viewsong' song.id %}">{{ song.title }}</a></td>
                <td><a href="{% url 'hashirim_shelanu:viewartist' song.artist.id %}">{{ song.artist.name }}</a></td>
                <td><a href="{% url 'hashirim_shelanu:viewprayer' song.prayer.id %}">{{ song.prayer.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
    {% if not song_list %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}

hashirim_shelanu/templates/hashirim_shelanu/viewartist.html
{% extends "tfilah_toolbox/base.html" %}
{% load static %}

{% block title %}Hashirim Shelanu | {{ artist.name }}{% endblock %}

{% block content %}
    <p><a href="#" onclick="history.back(); return false;">&lt; Go back</a></p>
    <h1>{{ artist }}</h1>
    <img src="{% if artist.picture %}{{ artist.picture.url }}{% else %}{% static 'hashirim_shelanu/Unknown-person.gif' %}{% endif %}" height="250" alt="{{ artist }}">
{% endblock %}

hashirim_shelanu/templates/hashirim_shelanu/viewprayer.html
{% extends "tfilah_toolbox/base.html" %}

{% block title %}Hashirim Shelanu | {{ prayer.name }}{% endblock %}

{% block content %}
    <p><a href="#" onclick="history.back(); return false;">&lt; Go back</a></p>
    <h1>{{ prayer.name }}</h1>
    <p>Tags:</p>
    <ul>
        {% for tag in prayer.tags.all %}
            <li>{{ tag }}</li>
        {% endfor %}
    </ul>
    <p>{{ prayer.description }}</p>
{% endblock %}

hashirim_shelanu/templates/hashirim_shelanu/viewsong.html
{% extends "tfilah_toolbox/base.html" %}
{% load static %}

{% block title %}Hashirim Shelanu | "{{ song.title }}" &mdash; {{ song.artist.name }}{% endblock %}

{% block meta %}
    <link rel="stylesheet" type="text/css" href="{% static 'hashirim_shelanu/viewsong.css' %}">
{% endblock %}

{% block content %}
    <div id="main-head">
        <p><a href="#" onclick="history.back(); return false;">&lt; Go back</a></p>
        <h2>{{ song.title }}</h2>
        <h3>{{ song.artist }}</h3>
        <p>Prayer: <b>{{ song.prayer.name }}</b></p>
        {% if chordsheet_html %}
            <form action="{% url 'hashirim_shelanu:download_chordpro' song.id %}" method="GET">
                <button type="submit">Download ChordPro</button>
            </form>
            <form action="{% url 'hashirim_shelanu:download_pdf' song.id %}" method="GET">
                <button type="submit">Download PDF</button>
            </form>
        {% endif %}
        <p>Tags:</p>
        <ul>
            {% for tag in song.tags.all %}
                <li>{{ tag }}</li>
            {% endfor %}
        </ul>
    </div>
    <div id="stream-links">
        {% if song.spotify %}
            <div id="spotify">
                <a href="https://open.spotify.com/track/{{ song.spotify }}">Listen on Spotify</a>
            </div>
        {% endif %}

        {% if song.apple_music %}
            <div id="apple-music">
                <a href="https://music.apple.com/us/album/{{ song.apple_music }}">Listen on Apple Music</a>
            </div>
        {% endif %}

        {% if song.youtube %}
            <div id="youtube">
                <a href="https://www.youtube.com/watch?v={{ song.youtube }}">Watch on YouTube</a>
            </div>
        {% endif %}
    </div>
    {% if chordsheet_html %}
        <div id="chordsheet">
            <div id="chordsheet-display">
                {{ chordsheet_html|safe }}
            </div>
            <div id="chordsheet-contributor">
                <i>Contributed by {{ song.chordsheet.list_contributors }}</i>
            </div>
        </div>
    {% endif %}
{% endblock %}